### ISSUE TITLE
Create 0.5.1j

### ISSUE THREAD

**Issue by xiewuzhiying** [ValkyrienSkies/Create-Interactive#16]

**Comment by blockninja124** [comment]
Create 0.5.1j marked us as incompatible in their mods.toml from what I can tell? Thats kinda tricky, not sure exactly how to fix that. (But then again I don't know much about the mods.toml system anyway)

**Comment by blockninja124** [comment]
https://github.com/Fabricators-of-Create/Create/blob/mc1.20.1/fabric/dev/src/main/resources/fabric.mod.json#L79 yup looks like thats the case. Wonder if they've done the same on forge, though I don't think its as easy to specify an incompatibility on forge.

**Comment by blockninja124** [comment]
They've since changed the breaks section to only be incompatible with current interactive versions, so since we've upped the version number once we release it should be fine with create 0.5.1j? Or I suppose once the next create update comes out with that change
