### ISSUE TITLE
Curved create tracks have bugged texture/model

### ISSUE THREAD

**Issue by blockninja124** [ValkyrienSkies/Create-Interactive#18]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

Whatever the heck is going on here
![image](https://github.com/user-attachments/assets/f59a15c6-da1a-4ef8-af8b-86406268f485)

This was on the xwyz/dev branch. I haven't seen if it happens on the main branch, but I assume it does?

**Comment by blockninja124** [comment]
Train bogeys also appear broken
![image](https://github.com/user-attachments/assets/1422a146-821e-4b43-8dec-15bccf53dbbc)

**Comment by xiewuzhiying** [comment]
I can't reproduce

**Comment by blockninja124** [comment]
Hmm it might've been me messing something up with porting lib when I reverted my create version locally so I could launch the game. How are you getting past the 0.5.1j incompatibility?
